language: node_js
node_js:
- '4.4'
- '6.9'
- '7.0'
env:
  matrix:
  - NODE_ENV=development
script: npm run coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
